name: flutter_ptcg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  async: ^2.11.0
  shared_preferences: ^2.0.6
  characters: ^1.3.0
  marquee: ^2.0.1 # 或者您需要的版本

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
